# Generated by Django 4.1.7 on 2023-02-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panthole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pant_photo', models.FileField(upload_to='panthole')),
                ('pant_latitude', models.FloatField()),
                ('pant_longitude', models.FloatField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
