# Generated by Django 4.1.7 on 2023-02-24 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Panthole',
            new_name='Pothole',
        ),
        migrations.RenameField(
            model_name='pothole',
            old_name='pant_latitude',
            new_name='pot_latitude',
        ),
        migrations.RenameField(
            model_name='pothole',
            old_name='pant_longitude',
            new_name='pot_longitude',
        ),
        migrations.RenameField(
            model_name='pothole',
            old_name='pant_photo',
            new_name='pot_photo',
        ),
    ]
