# Generated by Django 4.1.7 on 2023-02-27 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marker', '0002_rename_panthole_pothole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pothole',
            name='pot_description',
            field=models.TextField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
