# Generated by Django 4.1.7 on 2023-02-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marker', '0003_pothole_pot_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pothole',
            name='pot_photo',
            field=models.TextField(max_length=255),
        ),
    ]
